### ISSUE TITLE
Missing "developer" role

### ISSUE THREAD

**Issue by ginsterbusch** [GSA/accessibility-for-teams#31]
Either governmental sites appear magically out of nowhere, or you've just missed adding a "developer" role / use case.

And yes, web developers should indeed be included into improving accessibility of web sites, whether they are in the planning stage, or the actual implementation phase. As one would normally need to work on knitting the backend and frontend together, being prepared for a11y tasks is always a good choice. 

cu, w0lf.

**Comment by maya** [comment]
Hi @ginsterbusch, thanks so much for making this suggestion. Our team didn't have time to dive into backend developer roles yet, but we could consider this in the future. However, an understanding of the front-end developer role may help them get off to a good start since that is the layer folks will interact with. If you look at a similar guide by Google, [Accessibility for Teams: Developer](https://developers.google.com/web/fundamentals/accessibility/a11y-for-teams#developer), they have a lot of the same topics as we do in the Front-end developer guide.

We'd be glad to better understand the issues that backend developers face, so if you'd like to outline some specific areas, that would be a great start.

**Comment by maya** [comment]
Haven't heard back on this, closing.
