### ISSUE TITLE
WCAG 2+

### ISSUE THREAD

**Issue by mgifford** [GSA/accessibility-for-teams#41]
Curious if the accessibility guide is going to get updated to address WCAG 2.1 & updates from the W3C's Web Accessibility Initiative?

Many countries have adopted a WCAG 2+ policy framework so that the preferred guidelines are able to keep up with the internet. 

It is useful to know about, even if it isn't official policy.

**Comment by davidstenger** [comment]
The Access Board would have to go through all the procedures it took to refresh the old standards to WCAG 2.0 in order to adopt the WCAG 2.1 standards (or some large portion of them). As such, I don't expect the 508 standards would be refreshed anytime soon.

The WCAG 2.1 standard does not contradict 2.0 standards. So if you want to conform with the additional success criteria in WCAG 2.1 A/AA, then it would automatically conform with the WCAG 2.0 A/AA required under Section 508.   

Be reminded that the WCAG 2.0 A/AA standards included in Section refresh which became enforceable in Jan 2018 are minimum standards. Meaning, if you want to be more accessible you can choose to do that, but you can't do less. For example, I know web managers who require a higher contrast ratio than required; when the contrast ratio is tested for compliance to WCAG 2.0 A/AA ... it passes.

Needless to say, we can only require/enforce Section 508/WCAG 2.0 A/AA, but I don't see any reason why an agency couldn't set the bar higher.

**Comment by mgifford** [comment]
Would it be possible for this guide to point to the latest version of WCAG 2.  Not as a requirement as you say, but simply to point folks to the latest best practice for removing barriers to people with disabilities. I doubt that most organizations that are required to follow Section 508 are not even aware of WCAG 2+.

Thanks!

**Comment by davidstenger** [comment]
no issues pointing to the correct WCAG 2.0 guidelines. But Federal agencies must comply to section 508/WCAG 2.0 and yes a LARGE number of organizations don't even meet any section 508 or WCAG rules.

**Comment by mgifford** [comment]
It's a matter of priorities for many organizations. Unfortunately, for many organizations it just isn't there. :(
